apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-2
  labels:
    app: nginx
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
      ver: "2.0"
  template:
    metadata:
      labels:
        app: nginx
        ver: "2.0"
    spec:
      containers:
      - name: nginx
        image: vergeops/versioned-nginx:2.0
